# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatTest' do
  use_frameworks!
#Firebase

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'SideMenu'

# Facebook
pod 'FBSDKLoginKit'

pod 'MessageKit'
pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'

# Google Sign IN

pod 'GoogleSignIn'

#socket IO
pod 'Socket.IO-Client-Swift'

#cardSlider

pod 'CardSlider'

end
