# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoIt
#Firebase

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'SideMenu'

# Facebook
pod 'FBSDKLoginKit'

pod 'MessageKit'
pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'

# Google Sign IN

pod 'GoogleSignIn'

end
